<?php
return array (
  'id' => 20385,
  'id_firm' => 4087,
  'avtor' => 'КИЕВПЛАСТ',
  'e_mail_a' => 'info@okna.ua',
  'date_news' => '2019-06-12 15:40:27',
  'date_okonch' => NULL,
  'name' => 'Всем, кто запишется на замер с 13 по 19 июня',
  'text_news' => 'Всем, кто запишется на замер с 13 по 19 июня компания "КИЕВПЛАСТ" предоставляет скидку 34% + 3% на окна и двери дополнительно. Полученная скидка 37% фиксируется и действует в течение одной недели после замера!

Спешите! Предложение действительно только в течение трех дней!

Компания "КИЕВПЛАСТ" желает Вам солнечного настроения!',
  'ris' => 'img_news/kievplast/2-4087-64-20385-ris-vsem-kto-zapyshetsya-na-zamer-s-13-po-19-yyunya.jpg',
  'type_firm' => 9,
  'ris_sm' => NULL,
  'is_top' => 0,
  'url' => 'vsem-kto-zapyshetsya-na-zamer-s-13-po',
  'avtor_ua' => 'Київпласт',
  'avtor_en' => '',
  'name_ua' => 'Всім, хто запишеться на замір з 13 по 19 червня',
  'name_en' => '',
  'text_news_ua' => 'Всім, хто запишеться на замір з 13 по 19 червня компанія "Київпласт" надає знижку 34% + 3% на вікна та двері додатково. Отримана знижка 37% фіксується і діє протягом одного тижня після заміру!

Поспішайте! Пропозиція дійсна тільки протягом трьох днів!

Компанія "Київпласт" бажає Вам сонячного настрою!',
  'text_news_en' => '',
  'url_ua' => 'vsim-khto-zapyshetsya-na-zamir-z-13',
  'url_en' => '',
  'id_city' => -1,
  'address' => '',
  'address_ua' => '',
  'address_en' => '',
  'date_start' => '2019-06-13 00:00:00',
  'date_end' => '2019-06-19 00:00:00',
  'photograf' => '',
  'photograf_ua' => '',
  'photograf_en' => '',
  'id_expo' => -1,
  'is_uniq' => 0,
  'is_uniq_ua' => 0,
  'is_uniq_en' => 0,
  'date_formated' => '12.06.2019',
  'id_type' => -1,
  'id_group' => 6,
  'photo_descr' => '',
  'photo_descr_ua' => '',
  'photo_descr_en' => '',
  'action' => 0,
  'sale' => 37.0,
  'hidden' => 0,
  'source' => '',
  'source_url' => '',
  'chekit' => 1,
  'subhead' => '',
  'test' => 0,
  'dont_moderate' => 0,
  'id_yandex_original' => '',
  'yandex_original_error' => '',
  'id_yandex_original_ua' => '',
  'id_yandex_original_en' => '',
  'yandex_original_error_ua' => '',
  'yandex_original_error_en' => '',
  'notify' => 0,
  'url_ru' => 'vsem-kto-zapyshetsya-na-zamer-s-13-po',
  'city_detail' => false,
  'date_news_formated' => '12 июня 2019 г.',
  'date_start_end_formated' => '13—19 июня 2019',
  'some_time_ago' => '2 дня назад',
  'direct_link_ua' => 'https://okna.ua/ua/akcii/20190612/vsim-khto-zapyshetsya-na-zamir-z-13',
  'direct_link_en' => 'https://okna.ua/en',
  'direct_link_ru' => 'https://okna.ua/akcii/20190612/vsem-kto-zapyshetsya-na-zamer-s-13-po',
  'direct_link' => 'https://okna.ua/akcii/20190612/vsem-kto-zapyshetsya-na-zamer-s-13-po',
  'direct_link_amp' => 'https://okna.ua/akcii/20190612/vsem-kto-zapyshetsya-na-zamer-s-13-po/amp',
  'title_date' => '12 июня 2019 г., 15:40',
  'count_view' => '27',
);