<?php
return array (
  'id' => 610,
  'login' => 'login610',
  'password' => 'PASSWORD610',
  'date_reg' => '2010-10-04 08:44:28',
  'name' => 'ВДТ (Віконно-Дверні Технології)',
  'type_firm' => 1,
  'text_firm' => 'Пластиковые окна aluplast, Rehau, KBE, Kommerling, OpenTeck, остекление балконов. Двери, офисные перегородки и раздвижки из алюминия. Оплата частями.

Наша компания c 2003 года работает на рынке светопрозрачных конструкций Киева и Киевской области, и за это время зарекомендовала себя как поставщик качественных изделий и надежный исполнитель взятых на себя обязательств.
Предлагаемые <b>окна ПВХ</b> в состоянии удовлетворить любой «кошелек» и требования, как частного заказчика, так и корпоративного.
Изделия из профилей украинского производства Open Teck и WDS с фурнитурой WinkHaus прекрасно подойдут для остекления дач, школ, балконов и лоджий.
А конструкции из KBE, REHAU, aluplast и KOMMERLING (Кеммерлинг),  с фурнитурой Maco, WINKHAUS и Siegenia будут оптимальным выбором при остеклении квартиры или частного дома.',
  'text_firm_ua' => 'Пластикові вікна aluplast, Rehau, KBE, Kommerling, OpenTeck, засклення балконів. Вхідні двері, офісні перегородки та розсувні системи з алюмінію.

Наша компанія c 2003 року працює на ринку світлопрозорих конструкцій Києва і Київської області, і за цей час зарекомендувала себе як постачальник якісних виробів і надійний виконавець взятих на себе зобов\'язань.
Пропоновані <b> вікна ПВХ  в змозі задовольнити будь-який «гаманець» і вимоги, як приватного замовника, так і корпоративного.
Вироби з профілів українського виробництва Open Teck та WDS з фурнітурою WinkHaus чудово підійдуть для скління дач, шкіл, балконів і лоджій.
А конструкції з KBE, REHAU, aluplast і KOMMERLING (Кеммерлінг), з фурнітурою Maco, WINKHAUS і Siegenia будуть оптимальним вибором при склінні квартири або приватного будинку.',
  'machine_translate' => 0,
  'text_firm_en' => 'Plastic windows aluplast, Rehau, KBE, Kommerling, OpenTeck, glazing of balconies. Doors, office partitions and aluminum partitions. Payment in installments.

Since 2003, our company has been working in the market of translucent structures in Kyiv and the Kyiv region, and for this time has established itself as a supplier of quality products and a reliable performer of its obligations.
The proposed <b> PVC windows  are able to satisfy any "purse" and the requirements of both the private customer and the corporate.
Products made of Ukrainian profiles Open Teck, WDS with WinkHaus fittings are perfect for glazing dachas, schools, balconies and loggias.
And the designs from KBE, REHAU, aluplast and KOMMERLING (Kemmerling), with the accessories of Maco, WINKHAUS and Siegenia will be the best choice when glazing an apartment or a private house.',
  'contact' => 'Гармаш',
  'city' => 'Киев',
  'phone' => '(044)502-24-73, (095)921-18-87',
  'fax' => '+38 044 5022473',
  'e_mail' => 'wdt@okna.ua',
  'www_firm' => 'https://okna-wdt.com.ua',
  'logo' => 'tmp/1/wdt-logo.png',
  'type' => '',
  'cp' => -1,
  'chekit' => 1,
  'ip' => 'Нет',
  'product' => 0,
  'volum' => 0,
  'publ' => '0',
  'name_small' => '',
  'address1' => '',
  'address2' => 'пр-т Победы, 59а (2 этаж)',
  'address3' => '',
  'address1_ua' => '',
  'address1_en' => '',
  'address2_ua' => 'пр-т Перемоги, 59а (2 поверх)',
  'address2_en' => '',
  'address3_ua' => '',
  'address3_en' => '',
  'zip' => '03113',
  'm_phone' => '(098)904-75-04, (095)921-18-87,(093)258-23-58',
  'domen' => 'wdt',
  'licence' => NULL,
  'licence_giver' => NULL,
  'diller' => 1,
  'is_banner' => 0,
  'url_banner' => '',
  'sml_logo' => '',
  'not_hippercontext' => 0,
  'not_hippercontext_sys' => 0,
  'num_news' => 12,
  'num_akcii' => 6,
  'moderator' => '',
  'id_city' => 58,
  'id_country' => 1,
  'banner_on_mainpage' => 0,
  'www_dop' => 'www.facebook.com/okna.wdt/',
  'name_ua' => 'ВДТ (Віконно-Дверні Технології)',
  'name_en' => 'VDT (Vikonno-Dverni Tekhnolohiyi)',
  'id_forma_sob' => 7,
  'name_contact' => 'Владимир',
  'mname_contact' => 'Иванович',
  'date_reg_first' => '2003-03-14 00:00:00',
  'name_ru' => '',
  'trust_spam' => 0,
  'poddomen' => 'wdt',
  'activation_code' => '',
  'active' => 1,
  'new_email' => '',
  'email_activation_code' => '',
  'email_activation_date' => '0000-00-00 00:00:00',
  'show_comment' => 1,
  'id_metro' => 14,
  'id_region' => 161,
  'id_city_global' => 2813,
  'text_seo' => 'ВДТ (Віконно-Дверні Технології) располагает большим опытом на рынке металлопластиковых конструкций, а именно в сфере продаж и монтажа окон. За время своей деятельности в сегменте ВДТ (Віконно-Дверні Технології) приобрела хорошую репутацию среди потребителей, предлагая качественную продукцию по конкурентной цене. Индивидуальный подход к клиенту любого масштаба, грамотная ценовая политика, заказ в срок и с полным соблюдением заявленных технологий и правил – это основные характеристики сервиса. 
Металлопластиковые  окна из надежных и качественных материалов отечественных и зарубежных производителей – наше основное предложение в Киеве. В перечень нашей основной продукции входят профильные системы VEKA, KBE Fenstersysteme, REHAU, Koemmerling, GPS, ТМ. Качественная и долговечная фурнитура,  высококачественные стеклопакеты и уплотнители, используемые в изготовлении поставляемой нами продукции, нацелены на то, чтобы делать надежной и долговечной оконную конструкцию любой конфигурации. Консультация, предварительный замер, демонтаж и монтаж входят в спектр услуг компании ВДТ (Віконно-Дверні Технології).',
  'date_end' => '0000-00-00',
  'id_firm_dublicat' => 0,
  'watermark' => 1,
  'phone_stat' => 1,
  'send_post_comments' => 1,
  'google_plus_name' => 'ВДТ (ВІКОННО-ДВЕРНІ ТЕХНОЛОГІЇ)',
  'google_plus_page' => 'https://plus.google.com/+ВДТВІКОННОДВЕРНІТЕХНОЛОГІЇКиїв',
  'authors_text' => 1,
  'not_sending_email' => 0,
  'not_sending_stat' => 0,
  'hidden' => 0,
  'id_account' => 118,
  'edrpou' => '30318934',
  'date_edrpou' => '2019-01-03 00:00:00',
  'type_edrpou' => 2,
  'date_registr_edrpou' => '2006-02-16',
  'hide_reliability' => 0,
  'edrpou_hidden' => 0,
  'add_utm_source' => 1,
  'pl_num' => 0,
  'pl_num_ua' => 0,
  'pl_num_en' => 0,
  'member_energy_save' => 1,
  'gives_credit' => 1,
  'is_callback' => 1,
  'ga_id' => 'UA-73639933-1',
  'enable_ga_user_id' => 1,
  'phone_ask_sale' => 1,
  'security_class' => 1,
  'name_city' => 'Киев',
  'metro_style' => 'metro_kiev',
  'name_country' => 'Украина',
  'name_country_v' => 'Украине',
  'user_type' => 2,
  'id_section' => 5,
  'city_detail' => 
  array (
    'id' => 58,
    'id_country' => 1,
    'name' => 'Киев',
    'code' => '44',
    'name_ua' => 'Київ',
    'name_en' => 'Kyiv',
    'name_v' => 'Киеве',
    'id_region' => 161,
    'lng' => 30.523399352999999,
    'lat' => 50.4500999451,
    'sw_lng' => 30.297174453699999,
    'sw_lat' => 50.314281463599997,
    'ne_lng' => 30.765466690099998,
    'ne_lat' => 50.562923431400002,
    'name_v_ua' => 'Києві',
    'name_v_en' => 'Kyiv',
    'metro_style' => 'metro_kiev',
    'name_r' => 'Киева',
    'name_r_ua' => 'Києва',
    'name_r_en' => 'Kyiv',
    'south' => 50.213272094700002,
    'west' => 30.239440918,
    'north' => 50.5907974243,
    'east' => 30.8259410858,
    'domen' => 'kiev',
    'climat_zone' => 0,
    'fips' => '',
    'is_city' => true,
    'v_name' => 'в Киеве',
    'region_short' => false,
    'region_short_delimiter' => false,
    'region_short_markup' => false,
    'region_short_markup_delimiter' => false,
    'v_name_uniq' => 'в Киеве',
  ),
  'country_detail' => 
  array (
    'id' => 1,
    'name' => 'Украина',
    'name_ua' => 'Україна',
    'name_en' => 'Ukraine',
    'img_flag' => 'img/Ukraine.gif',
    'name_v' => 'Украине',
    'sw_lng' => 28.002962112399999,
    'sw_lat' => 44.453277587899997,
    'ne_lng' => 34.372100830100003,
    'ne_lat' => 52.601131439200003,
    'prior' => 1,
    'climat_zone' => 1,
    'name_r' => 'Украины',
    'name_r_ua' => 'України',
    'name_r_en' => 'Ukraine',
    'name_v_ua' => 'Україні',
    'name_v_en' => 'Ukraine',
    'lat' => 48.379432678199997,
    'lng' => 31.165580749499998,
    'south' => 44.3864631653,
    'west' => 22.137159347499999,
    'north' => 52.3795814514,
    'east' => 40.228580474899999,
    'domen' => 'ukraine',
    'is_city' => false,
    'v_name' => 'в Украине',
    'v_name_uniq' => 'в Украине',
  ),
  'group_detail' => 
  array (
    'id' => 2,
    'prior' => 1,
    'name' => 'Окна',
    'name_ua' => 'Вікна',
    'name_en' => 'Windows',
    'domen' => 'okna',
    'subdomen' => '',
    'prior_filter' => 0,
    'prior_maps' => 1,
    'prior_registration' => 1,
    'description' => 'Каталог производителей и поставщиков ПВХ, алюминиевых, деревянных окон',
    'description_ua' => 'Каталог виробників і постачальників ПВХ, алюмінієвих, дерев\'яних вікон',
    'description_en' => 'Product manufacturers and suppliers of PVC, aluminum, wood windows',
    'is_publik' => 1,
    'is_brands' => 1,
    'name_v' => 'окон',
    'name_v_ua' => 'вікон',
    'name_v_en' => 'windows',
    'top_menu' => 1,
    'top_description' => 'производителей окон, поставщиков',
    'top_description_ua' => 'виробників вікон, постачальників',
    'top_description_en' => 'window manufacturers, vendors',
    'domen-catalog' => 'okna',
    'direct_link' => 'https://okna.ua/okna/',
    'direct_link_w_delimiter' => 'https://okna.ua/okna/',
  ),
  'forma_sob_detail' => 
  array (
    'id' => 7,
    'name' => 'ЧП',
    'name_ua' => 'ЧП',
    'name_en' => 'PE',
  ),
  'www' => 'https://okna-wdt.com.ua',
  'phonem' => '(098)904-75-04, (095)921-18-87,(093)258-23-58',
  'logo_catalog' => 'tmp/1/wdt-logo-100x60.png',
  'catalog_name' => 'Окна',
  'forma_sob' => '',
  'is_accessible' => true,
  'direct_link' => 'https://wdt.okna.ua/',
  'direct_link_map' => 'https://wdt.okna.ua/map',
  'direct_link_pricelist' => 'https://wdt.okna.ua/price/',
  'direct_link_pricelist_firm' => 'price',
  'direct_link_video' => 'https://wdt.okna.ua/video/',
  'metro_name' => 'Берестейская',
  'f_fax' => '+38 044 5022473',
  'f_m_phone' => '(098)904-75-04, (095)921-18-87,(093)258-23-58',
  'f_phone' => '(044)502-24-73, (095)921-18-87',
  'text' => 'Пластиковые окна aluplast, Rehau, KBE, Kommerling, OpenTeck, остекление балконов. Двери, офисные перегородки и раздвижки из алюминия. Оплата частями.

Наша компания c 2003 года работает на рынке светопрозрачных конструкций Киева и Киевской области, и за это время зарекомендовала себя как поставщик качественных изделий и надежный исполнитель взятых на себя обязательств.
Предлагаемые <b>окна ПВХ</b> в состоянии удовлетворить любой «кошелек» и требования, как частного заказчика, так и корпоративного.
Изделия из профилей украинского производства Open Teck и WDS с фурнитурой WinkHaus прекрасно подойдут для остекления дач, школ, балконов и лоджий.
А конструкции из KBE, REHAU, aluplast и KOMMERLING (Кеммерлинг),  с фурнитурой Maco, WINKHAUS и Siegenia будут оптимальным выбором при остеклении квартиры или частного дома.',
  'fio' => 'Владимир Иванович',
  'ava' => '<a href="https://wdt.okna.ua/">
                <img src="https://okna.ua/tmp/1/wdt-logo.png" width="50"/>
                </a>',
  'ava_block' => '<div class="ava_block_left_nice_form"><a href="https://wdt.okna.ua/">
                <img src="https://okna.ua/tmp/1/wdt-logo.png" width="50"/>
                </a><br /><a href="https://wdt.okna.ua/">ВДТ (Віконно-Дверні Технології)</a></div>',
  'translator' => 0,
  'packet_detail' => 
  array (
    'id' => '7',
    'name' => 'Базовый',
    'name_ua' => 'Базовий',
    'name_en' => 'Base',
    'id_type' => '0',
    'level' => '0',
    'edit_page_show' => '0',
    'pow' => '0',
    'foto' => '5',
    'foto_min' => '5',
    'okna_price' => '1',
    'okna_price_min' => '1',
    'price' => '10',
    'price_min' => '5',
    'video' => '1',
    'video_min' => '0',
    'doptext' => '0',
    'doptext_min' => '0',
    'bu' => '0',
    'bu_min' => '0',
    'seo' => '0',
    'seo_min' => '0',
    'text' => '1000',
    'text_min' => '500',
    'news' => '6.5',
    'news_min' => '30',
    'subs' => '100000',
    'subs_min' => '15',
    'board' => '25',
    'board_min' => '1',
    'sep' => '0',
    'sep_min' => '0',
    'sep_promo' => '0',
    'okna_price_catalog' => '0',
    'okna_prica_catalog_min' => '0',
    'ads_budget' => '0',
    'art_on_index' => '0',
    'enable_okna' => '1',
    'enable_bau' => '1',
    'enable_decor' => '1',
    'enable_truba' => '1',
    'enable_tipografia' => '1',
    'enable_okna_kz' => '1',
    'enable_okna_rf' => '1',
    'enable_okna_by' => '1',
    'enable_findmewindow' => '1',
    'enable_windows_au' => '1',
    'enable_fenster_de' => '1',
  ),
  'firm_groups_block' => 
  array (
    0 => '<div class="it">Подразделы: </div><div><div class="span3"><div class="lbs fl firm_type pvc">Металлопластиковые окна </div></div><div class="span3"><div class="lbs fl firm_type al">Алюминиевые окна </div></div><div class="clr"></div></div>',
    1 => 'металлопластиковых окон, алюминиевых окон',
  ),
  'tm_usage' => 
  array (
    14 => '<a href="https://okna.ua/osnova" class="i">Osnova</a>',
    16 => '<a href="https://okna.ua/osnova" class="i">Osnova</a>',
    18 => '<a href="https://kbe.okna.ua/" class="i">KBE</a>, <a href="https://okna.ua/koemmerling" class="i">KÖMMERLING</a>, <a href="https://aluplast.okna.ua/" class="i">aluplast GmbH</a>',
    19 => '<a href="https://okna.ua/winkhaus" class="i">WINKHAUS</a>, <a href="https://maco.okna.ua/" class="i">MACO</a>, <a href="https://okna.ua/vorne" class="i">VORNE</a>',
    21 => '<a href="https://okna.ua/euroglas" class="i">Euroglas GmbH</a>, <a href="https://okna.ua/stadur" class="i">STADUR</a>, <a href="https://okna.ua/guardian" class="i">Guardian Global Headquarters</a>',
    23 => '<a href="https://okna.ua/winkhaus" class="i">WINKHAUS</a>, <a href="https://okna.ua/adgroup" class="i">RasKon (Расчет Конструкций)</a>, <a href="https://okna.ua/vsgroup" class="i">WinCalc</a>',
    49 => '<a href="https://okna.ua/altest" class="i">ALTEST</a>',
    '14_txt' => 'Osnova',
    '16_txt' => 'Osnova',
    '18_txt' => 'KBE, KÖMMERLING, aluplast GmbH',
    '19_txt' => 'WINKHAUS, MACO, VORNE',
    '21_txt' => 'Euroglas GmbH, STADUR, Guardian Global Headquarters',
    '23_txt' => 'WINKHAUS, RasKon (Расчет Конструкций), WinCalc',
    '49_txt' => 'ALTEST',
    'overall' => '<a href="https://okna.ua/osnova" class="i">Osnova</a>, <a href="https://okna.ua/osnova" class="i">Osnova</a>, <a href="https://kbe.okna.ua/" class="i">KBE</a>',
    'overall_txt' => 'Osnova, Osnova, KBE',
  ),
  'firm_geo_marker' => 
  array (
    0 => 
    array (
      'position' => 
      array (
        'lat' => 50.458385,
        'lng' => 30.417206,
        'name' => 'ВДТ (Віконно-Дверні Технології)',
        'directLink' => 'https://wdt.okna.ua/',
        'address' => 'пр-т Победы, 59а (2 этаж)',
      ),
    ),
  ),
);
