<?php
return array (
  'id' => 20386,
  'id_firm' => 925,
  'avtor' => 'Галина Коноваленко',
  'e_mail_a' => 'info@okna.ua',
  'date_news' => '2019-06-13 15:42:06',
  'date_okonch' => NULL,
  'name' => 'На «теплые кредиты» для ОСМД планируется выделить дополнительные 380,7 млн грн',
  'text_news' => '<p>Об&nbsp;этом на&nbsp;своей <nobr>фейсбук-странице</nobr> сообщил <nobr>Вице-премьер-министр</nobr> Министр регионального развития, строительства и&nbsp;<acronym title="Жилищно-коммунальное хозяйство" lang="ru">ЖКХ</acronym> Украины Геннадий Зубко. Правительственный комитет по&nbsp;вопросам европейской, евроатлантической интеграции, международного сотрудничества и&nbsp;регионального развития поддержал решение о&nbsp;дополнительном финансировании государственной программы энергоэффективности &laquo;теплые кредиты&raquo;.<br />
&laquo;Программа &bdquo;теплые кредиты&ldquo; будет продлена. Спасибо Правительственному комитету по&nbsp;вопросам европейской, евроатлантической интеграции, международного сотрудничества и&nbsp;регионального развития за&nbsp;поддержку нашего решения о&nbsp;выделении дополнительного финансирования на&nbsp;программу &bdquo;теплых кредитов&ldquo; в&nbsp;сумме почти 380,7&nbsp;млн грн&raquo;,&nbsp;&mdash; написал Геннадий Зубко.<br />
Читайте также: <a href="https://okna.ua/library/kak-proveryt-enerhoeffektyvnost-okna">Инструкция: как проверить энергосберегающие окна?<br /></a>
Он&nbsp;также отметил, что соответствующее постановление и&nbsp;распоряжение будут вынесены на&nbsp;рассмотрение на&nbsp;следующем заседании правительства.<br />
Вчера Геннадий Зубко отметил: «Хочу успокоить ОСМД по ситуации с программой &bdquo;теплых кредитов&ldquo;. Поручил подготовить решение правительства о дополнительном финансировании программы в размере почти 380,7 млн грн».
Напомним, что в&nbsp;2019 на&nbsp;государственную программу энергоэффективности было <a href="https://okna.ua/news/20190313/teplye-kredyty-2019-snova-400-mln">выделено</a> 400&nbsp;млн грн. Средства закончились за&nbsp;первые четыре месяца.</p>',
  'ris' => 'img_news/oknaua/2-925-5-20386-ris-na-teplye-kredyty-dlya-osmd-planyruetsya.jpeg',
  'type_firm' => 9,
  'ris_sm' => NULL,
  'is_top' => 0,
  'url' => 'na-teplye-kredyty-dlya-osmd',
  'avtor_ua' => 'Галина Коноваленко',
  'avtor_en' => '',
  'name_ua' => 'На «теплі кредити» для ОСББ планується виділити додаткові 380,7 млн грн',
  'name_en' => '',
  'text_news_ua' => '<p>Про це&nbsp;на&nbsp;своїй <nobr>фейсбук-сторінці</nobr> повідомив <nobr>Віцепрем</nobr>&rsquo;<nobr>єр-міністр</nobr> Міністр регіонального розвитку, будівництва та&nbsp;ЖКГ України Геннадій Зубко. Урядовий комітет з&nbsp;питань європейської, євроатлантичної інтеграції, міжнародного співробітництва та&nbsp;регіонального розвитку підтримав рішення щодо додаткового фінансування державної програми енергоефективності &laquo;теплі кредити&raquo;.<br />
&laquo;Програму &bdquo;теплі кредити&ldquo; буде продовжено. Дякую Урядовому комітету з&nbsp;питань європейської, євроатлантичної інтеграції, міжнародного співробітництва та&nbsp;регіонального розвитку за&nbsp;підтримку нашого рішення щодо виділення додаткового фінансування програми &bdquo;теплих кредитів&ldquo; у&nbsp;сумі майже 380,7&nbsp;млн грн&raquo;,&nbsp;&mdash; написав Геннадій Зубко.<br />
Читайте також: <a href="https://okna.ua/ua/library/yak-pereviryty-enerhoefektyvnist-vikna">Інструкція: як&nbsp;перевірити енергоощадні вікна?<br /></a>
Він також зазначив, що&nbsp;відповідна постанова та&nbsp;розпорядження будуть винесені на&nbsp;розгляд на&nbsp;наступному засіданні Уряду.<br />
Вчора Геннадій Зубко зазначив: «Хочу заспокоїти ОСББ щодо ситуації з програмою&bdquo;теплих кредитів&ldquo;. Доручив підготувати рішення Уряду щодо додаткового фінансування програми у розмірі майже 380,7 млн грн». 
Нагадаємо, що&nbsp;на&nbsp;2019 рік на&nbsp;державну програму енергоефективності було <a href="https://okna.ua/ua/news/20190313/tepli-kredyty-2019-znov-400-mln-hrn">виділено</a> 400&nbsp;млн грн. Кошти закінчились за&nbsp;перші чотири місяці.</p>',
  'text_news_en' => '',
  'url_ua' => 'na-tepli-kredyty-dlya-osbb',
  'url_en' => '',
  'id_city' => -1,
  'address' => '',
  'address_ua' => '',
  'address_en' => '',
  'date_start' => '0000-00-00 00:00:00',
  'date_end' => '0000-00-00 00:00:00',
  'photograf' => '',
  'photograf_ua' => '',
  'photograf_en' => '',
  'id_expo' => -1,
  'is_uniq' => 0,
  'is_uniq_ua' => 0,
  'is_uniq_en' => 0,
  'date_formated' => '13.06.2019',
  'id_type' => -1,
  'id_group' => -1,
  'photo_descr' => '',
  'photo_descr_ua' => '',
  'photo_descr_en' => '',
  'action' => 0,
  'sale' => 0.0,
  'hidden' => 0,
  'source' => '',
  'source_url' => '',
  'chekit' => 1,
  'subhead' => '',
  'test' => 0,
  'dont_moderate' => 1,
  'id_yandex_original' => '',
  'yandex_original_error' => '',
  'id_yandex_original_ua' => '',
  'id_yandex_original_en' => '',
  'yandex_original_error_ua' => '',
  'yandex_original_error_en' => '',
  'notify' => 1,
  'url_ru' => 'na-teplye-kredyty-dlya-osmd',
  'city_detail' => false,
  'date_news_formated' => '13 июня 2019 г.',
  'date_start_end_formated' => '',
  'some_time_ago' => '12 часов назад',
  'direct_link_ua' => 'https://okna.ua/ua/news/20190613/na-tepli-kredyty-dlya-osbb',
  'direct_link_en' => 'https://okna.ua/en',
  'direct_link_ru' => 'https://okna.ua/news/20190613/na-teplye-kredyty-dlya-osmd',
  'direct_link' => 'https://okna.ua/news/20190613/na-teplye-kredyty-dlya-osmd',
  'direct_link_amp' => 'https://okna.ua/news/20190613/na-teplye-kredyty-dlya-osmd/amp',
  'title_date' => '13 июня 2019 г., 15:42',
  'count_view' => '211',
);