<?php
return array (
  0 => 
  array (
    'id' => '14',
    'type_firm' => '1',
    'name' => 'Металлопластиковые окна',
    'name_ua' => 'Металопластикові вікна',
    'domen' => 'pvc',
    'prior' => '1',
    'description' => 'Пластиковые окна и двери со стеклопакетами',
    'description_ua' => 'Пластикові вікна і двері зі склопакетами',
    'description_en' => 'Plastic windows and doors with glass',
    'name_v' => 'металлопластиковых окон',
    'name_v_ua' => 'металопластикових вікон',
    'name_v_en' => 'plastic windows',
    'name_r' => '',
    'sub_type' => '0',
    'name_en' => 'Plastic windows',
    'title' => 'Металлопластиковые окна.',
    'title_ua' => 'Металопластикові вікна.',
    'title_en' => 'Plastic windows.',
    'top_menu' => '1',
    'name_short' => '',
    'name_short_ua' => '',
    'name_short_en' => '',
    'sys_type' => '1',
  ),
  1 => 
  array (
    'id' => '16',
    'type_firm' => '1',
    'name' => 'Алюминиевые окна',
    'name_ua' => 'Алюмінієві вікна',
    'domen' => 'al',
    'prior' => '2',
    'description' => 'Окна из "теплых" и "холодных" алюминиевых профильных систем',
    'description_ua' => 'Вікна з "теплих" і "холодних" алюмінієвих профільних систем',
    'description_en' => 'Windows made of "warm" and "cold" aluminum profile systems',
    'name_v' => 'алюминиевых окон',
    'name_v_ua' => 'алюмінієвих вікон',
    'name_v_en' => 'aluminum windows',
    'name_r' => '',
    'sub_type' => '0',
    'name_en' => 'Aluminium windows',
    'title' => 'Алюминиевые окна. Алюминиевый профиль для окон, производство и цены на раздвижные алюминиевые окна.',
    'title_ua' => 'Алюмінієві вікна. Алюмінієвий профіль для вікон, виробництво і ціни на розсувні алюмінієві вікна.',
    'title_en' => 'Aluminium windows. Aluminium profiles for windows, production and prices sliding aluminum windows.',
    'top_menu' => '1',
    'name_short' => '',
    'name_short_ua' => '',
    'name_short_en' => '',
    'sys_type' => '2',
  ),
  2 => 
  array (
    'id' => '15',
    'type_firm' => '1',
    'name' => 'Деревянные окна',
    'name_ua' => 'Дерев\'яні вікна',
    'domen' => 'wood',
    'prior' => '3',
    'description' => 'Деревянные окна и двери, окна из евробруса.',
    'description_ua' => 'Дерев\'яні вікна та двері, вікна з євробрусу.',
    'description_en' => 'Wooden windows and doors, windows eurobar.',
    'name_v' => 'деревянных окон',
    'name_v_ua' => 'дерев\'яних вікон',
    'name_v_en' => 'wooden windows',
    'name_r' => '',
    'sub_type' => '0',
    'name_en' => 'Wooden windows',
    'title' => 'Деревянные окна. Производство и изготовление деревянных окон со стеклопакетами, цены и стоимость. Производители деревянных окон.',
    'title_ua' => 'Дерев\'яні вікна. Виробництво і виготовлення дерев\'яних вікон зі склопакетами, ціни і вартість. Виробники дерев\'яних вікон.',
    'title_en' => 'Wooden windows. Manufacturing and production of wooden windows with double-glazed, prices and costs. Manufacturers of wooden windows.',
    'top_menu' => '1',
    'name_short' => '',
    'name_short_ua' => '',
    'name_short_en' => '',
    'sys_type' => '3',
  ),
);