<?php
return array (
  'id' => 2,
  'prior' => 1,
  'name' => 'Окна',
  'name_ua' => 'Вікна',
  'name_en' => 'Windows',
  'domen' => 'okna',
  'subdomen' => '',
  'prior_filter' => 0,
  'prior_maps' => 1,
  'prior_registration' => 1,
  'description' => 'Каталог производителей и поставщиков ПВХ, алюминиевых, деревянных окон',
  'description_ua' => 'Каталог виробників і постачальників ПВХ, алюмінієвих, дерев\'яних вікон',
  'description_en' => 'Product manufacturers and suppliers of PVC, aluminum, wood windows',
  'is_publik' => 1,
  'is_brands' => 1,
  'name_v' => 'окон',
  'name_v_ua' => 'вікон',
  'name_v_en' => 'windows',
  'top_menu' => 1,
  'top_description' => 'производителей окон, поставщиков',
  'top_description_ua' => 'виробників вікон, постачальників',
  'top_description_en' => 'window manufacturers, vendors',
  'domen-catalog' => 'okna',
  'direct_link' => 'https://okna.ua/okna/',
  'direct_link_w_delimiter' => 'https://okna.ua/okna/',
);